#!/bin/bash
# skate-to-omarchy.sh
# Export skate secrets and generate a script to populate skate on Omarchy

SKATE_ENV="${HOME}/.skate_env"

usage() {
    echo "Usage: $(basename $0) [output-file]"
    echo ""
    echo "Reads from: $SKATE_ENV"
    echo "Outputs a script that runs 'skate set <key> <value>' on Omarchy"
    echo ""
    echo "Copy the output script to Omarchy and run it there."
    exit 1
}

SCRIPT_FILE="${1:-skate-omarchy-setup.sh}"

if [ ! -f "$SKATE_ENV" ]; then
    echo "ERROR: $SKATE_ENV not found"
    exit 1
fi

echo "=== Skate to Omarchy Export ==="
echo "Source: $SKATE_ENV"
echo "Output: $SCRIPT_FILE"
echo ""

KEY_COUNT=$(grep -c "^export " "$SKATE_ENV" || echo 0)
echo "Found $KEY_COUNT keys"
echo ""

# Build the script
cat > "$SCRIPT_FILE" << 'HEADER'
#!/bin/bash
# Skate setup script for Omarchy
# Generated by scripts/skate-to-omarchy.sh
# DELETE AFTER RUNNING

set -e

echo "Setting skate keys..."
HEADER

# Check if skate is installed first
cat >> "$SCRIPT_FILE" << 'CHECK'
if ! command -v skate &> /dev/null; then
    echo "ERROR: skate not found on this system"
    echo "Install skate first, then run this script."
    exit 1
fi
CHECK

# Parse each export line
grep "^export " "$SKATE_ENV" | while IFS= read -r line; do
    rest="${line#export }"
    name="${rest%%=*}"
    value="${rest#*=}"
    
    if [ "$value" = "$name" ]; then
        continue
    fi
    
    # Escape for shell - use printf for safety with special chars
    # We'll use a heredoc-safe approach: write each key to a temp file, read it back
    echo "printf '%s' '$value' | skate set '$name' --stdin" >> "$SCRIPT_FILE"
done

# Add footer
cat >> "$SCRIPT_FILE" << 'FOOTER'

echo "Done. $(skate list 2>/dev/null | grep -c '.' || echo 0) keys set."
FOOTER

chmod +x "$SCRIPT_FILE"

EXPORTED=$(grep -c "skate set" "$SCRIPT_FILE" || echo 0)

echo "=== Script ready: $SCRIPT_FILE ==="
echo "Will set: $EXPORTED keys"
echo ""

echo "Keys:"
grep "skate set" "$SCRIPT_FILE" | sed "s/skate set '//" | sed "s/'.*//" | sort | while read k; do
    echo "  $k"
done

echo ""
echo "=== Next steps ==="
echo "1. Copy $SCRIPT_FILE to Omarchy"
echo "2. On Omarchy: bash $SCRIPT_FILE"
echo "3. Verify: skate list"
echo "4. Delete $SCRIPT_FILE: rm $SCRIPT_FILE"
echo ""
echo "⚠️  DELETE THE SCRIPT AFTER RUNNING — it contains secrets!"