#!/bin/bash
# skate-to-omarchy.sh
# Export all skate secrets to a script for Omarchy

# The source file
SKATE_ENV="${HOME}/.skate_env"

usage() {
    echo "Usage: $(basename $0) [output-file]"
    echo ""
    echo "Reads from: $SKATE_ENV"
    echo "Outputs a shell script with all skate key-value pairs"
    echo ""
    echo "Copy the output script to Omarchy and run it there."
    echo "Then: rm the-script.sh"
    exit 1
}

SCRIPT_FILE="${1:-skate-omarchy-setup.sh}"

# Check source
if [ ! -f "$SKATE_ENV" ]; then
    echo "ERROR: $SKATE_ENV not found"
    echo "Your skate secrets aren't in the expected location."
    exit 1
fi

echo "=== Skate to Omarchy Export ==="
echo "Source: $SKATE_ENV"
echo "Output: $SCRIPT_FILE"
echo ""

# Count keys
KEY_COUNT=$(grep -c "^export " "$SKATE_ENV" || echo 0)
echo "Found $KEY_COUNT keys"
echo ""

# Build the script
cat > "$SCRIPT_FILE" << 'HEADER'
#!/bin/bash
# Skate secrets for Omarchy
# Generated by scripts/skate-to-omarchy.sh
# DELETE AFTER RUNNING

set -e
HEADER

# Parse each export line
grep "^export " "$SKATE_ENV" | while IFS= read -r line; do
    # Extract variable name and value
    # Format: export NAME=value
    # Value may contain = (for keys like fal_api_key=...:...)
    
    # Remove "export " prefix
    rest="${line#export }"
    
    # Find first = after the variable name
    # Variable name is everything up to the first = after the name
    # But variable names don't contain =, so find the first =
    name="${rest%%=*}"
    value="${rest#*=}"
    
    # Check for empty value (line ends with "export NAME=")
    if [ "$value" = "$name" ]; then
        continue  # skip empty values
    fi
    
    # Escape single quotes for shell safety
    value_escaped=$(echo "$value" | sed "s/'/'\\''/g")
    
    echo "export ${name}='${value_escaped}'" >> "$SCRIPT_FILE"
done

# Add footer
cat >> "$SCRIPT_FILE" << 'FOOTER'

echo "Done. $# keys loaded."
FOOTER

chmod +x "$SCRIPT_FILE"

# Count exported
EXPORTED=$(grep -c "^export " "$SCRIPT_FILE" || echo 0)

echo "=== Script ready: $SCRIPT_FILE ==="
echo "Exported: $EXPORTED keys"
echo ""

echo "Keys:"
grep "^export " "$SCRIPT_FILE" | sed "s/^export \(.*\)=.*/\1/" | sort | while read k; do
    echo "  $k"
done

echo ""
echo "=== Next steps ==="
echo "1. Copy $SCRIPT_FILE to Omarchy"
echo "2. On Omarchy: bash $SCRIPT_FILE"
echo "3. Add to ~/.bashrc:"
echo "   grep -v '^#' $SCRIPT_FILE >> ~/.bashrc"
echo "4. Delete $SCRIPT_FILE: rm $SCRIPT_FILE"
echo ""
echo "⚠️  DELETE THE SCRIPT AFTER RUNNING — it contains secrets!"