Set Shell zsh
Sleep 6.5s
Type "glow"
Sleep 2s
Enter
Sleep 1s
Down
Sleep 2.5s
Type "/"
Sleep 500ms
Type "202"
Sleep 1s
Type "6-"
Sleep 2s
Type "08-01"
Sleep 1.5s
Down
Sleep 1.5s
Down
Sleep 2s
Enter
Sleep 6s
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Escape
Type "[<2;71;19M"
Escape
Type "[<2;71;19m"
Sleep 1s
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Escape
Type "[<2;71;19M"
Escape
Type "[<2;71;19m"
Sleep 500ms
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Escape
Type "[<65;71;19M"
Sleep 4s
Type "q"
Sleep 1s
Type "exit"

